### Title :- Data Preprocessing Reading the Dataset Handling Missing Data Conversion to the Tensor Format.

Step 1) Reading the Dataset:

          name  age  gender  salary
0     John Doe   30    Male   60000
1   Jane Smith   25  Female   55000
2  Bob Johnson   35    Male   75000
3  Alice Brown   28  Female   62000
4  Michael Lee   32    Male   68000
5   Ella Davis   29  Female   58000 

save this as data exp3.csv

In [1]:
import pandas as pd
#Read a CSV file into a Pandas DataFrame 
df = pd.read_csv("2exp.csv") 
print(df)

          name  age  gender  salary
0     John Doe   30    Male   60000
1   Jane Smith   25  Female   55000
2  Bob Johnson   35    Male   75000
3  Alice Brown   28  Female   62000
4  Michael Lee   32    Male   68000
5   Ella Davis   29  Female   58000


Step 2) Handling Missing Data: 


In [2]:
# Check for missing values in the DataFrame 
print(df.isnull().sum())
# Option 1: Drop rows with missing values 
#df = df.drop()

#Option 2: Fill missing values with a specific value (e.g., mean, median, or custom value) 
mean_age= df['age'].mean() 
df['age'].fillna(mean_age, inplace=True) 
#df = pd.DataFrame(df)

df["gender"] = df ["gender"].map({'Male':1, 'Female':0}) 
print(df)

name      0
age       0
gender    0
salary    0
dtype: int64
          name  age  gender  salary
0     John Doe   30       1   60000
1   Jane Smith   25       0   55000
2  Bob Johnson   35       1   75000
3  Alice Brown   28       0   62000
4  Michael Lee   32       1   68000
5   Ella Davis   29       0   58000


Step 3) Conversion to the Tensor Format:

In [5]:
import numpy as np 
import tensorflow as tf

# Extract features and Labels from the DataFrame 
X=df[['age', 'gender']].values 
y=df['salary'].values

# Convert to TensorFlow tensors
X_tensor = tf.constant(X, dtype=tf.float32)
y_tensor = tf.constant(y, dtype=tf.int32)

print("\n X tensor \n",X_tensor) 
print("\n Y tensor\n",y_tensor)


 X tensor 
 tf.Tensor(
[[30.  1.]
 [25.  0.]
 [35.  1.]
 [28.  0.]
 [32.  1.]
 [29.  0.]], shape=(6, 2), dtype=float32)

 Y tensor
 tf.Tensor([60000 55000 75000 62000 68000 58000], shape=(6,), dtype=int32)


In [4]:
# Alternatively, you can use NumPy arrays directly as TensorFlow tensors 

X_tensor = tf.convert_to_tensor (X, dtype=tf.float32)
y_tensor = tf.convert_to_tensor (y, dtype=tf.int32)
print("\n X tensor \n",X_tensor) 
print("\n Y tensor\n",y_tensor)


 X tensor 
 tf.Tensor(
[[30.  1.]
 [25.  0.]
 [35.  1.]
 [28.  0.]
 [32.  1.]
 [29.  0.]], shape=(6, 2), dtype=float32)

 Y tensor
 tf.Tensor([60000 55000 75000 62000 68000 58000], shape=(6,), dtype=int32)
