### Linear Algebra Tensors - Tensor Arithmetic ( Implementing matrix multiplication )

In [4]:
# Using Numpy

import numpy as np
# 1-D tensor (vector) 
vector = np.array([1, 2, 3])

# 2-D tensor (matrix) 
matrix = np.array([[1, 2], [3, 4]])

# 3-D tensor 
tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Create tensors (multi-dimensional arrays) using NumPy
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print('tensor_a\n',a)
print('tensor_b\n',b)

tensor_a
 [[1 2]
 [3 4]]
tensor_b
 [[5 6]
 [7 8]]


In [5]:
# Addition
tensor_sum = a + b
print("Sum of tensors:\n",tensor_sum)

# Scalar multiplication
scalar = 2
tensor_scaled = scalar * a
print("\nScalar multiplication:\n",tensor_scaled)

# Element-wise multiplication
tensor_product = np.multiply(a,b) #a*b
print("\nElement-wise multiplication:\n",tensor_product)

#matrix multiplication
dot_product=a@b # equivalent to np.dot(a,b)
print("\nMatrix multiplication:\n",dot_product)

Sum of tensors:
 [[ 6  8]
 [10 12]]

Scalar multiplication:
 [[2 4]
 [6 8]]

Element-wise multiplication:
 [[ 5 12]
 [21 32]]

Matrix multiplication:
 [[19 22]
 [43 50]]


In [6]:
# Using Tensorflow

import tensorflow as tf

# Create tensors using TensorFlow
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# Addition
tensor_sum = tf.math.add(tensor_a, tensor_b)
print("Sum of tensors:\n",tensor_sum)

# Scalar multiplication
scalar = 2
tensor_scaled = tf.math.scalar_mul(scalar, tensor_a)
print("Scalar multiplication:\n",tensor_scaled)

# Element-wise multiplication
tensor_product = tf.math.multiply(tensor_a, tensor_b)
print("\nElement-wise multiplication:\n",tensor_product)

#dot product
dot_product = tf.linalg.matmul(tensor_a, tensor_b)
print("\nDot Product:\n",dot_product)

Sum of tensors:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Scalar multiplication:
 tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)

Element-wise multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)

Dot Product:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
