### #6 :- Forward pass with matrix multiplication Forward pass with hidden layer (matrix multiplication)  Forward pass with matrix multiplication with Keras Forward passes with hidden layer (matx
 multiplication) with Keras. s.ediction}"main()


1) Forward Pass with Matrix Multiplication in Keras (Single-Layer Neural Network). 
2) Define a Keras model with a single layer: model 
3) To perform the forward pass and obtain the output. 
4) Forward Pass with Hidden Layer in Keras (Multi-Layer Neural Network): 
5) Create input data. 
6) Define a Keras model with a hidden layer and an output layer. 
7) To perform the forward pass and obtain the output. 

In [1]:
# 1. Forward Pass with Matrix Multiplication (Without Hidden Layer)

import numpy as np

# Input data (a 3x2 matrix)
input_data = np.array([[1, 2],
                       [3, 4], 
                       [5, 6]])
# Weight matrix (a 2x2 matrix) 
weights = np.array([[0.1, 0.2], 
                    [0.3, 0.4]])

# Forward pass without a hidden Layer (matrix multiplication) 
output_data = np.dot (input_data, weights)

print("Output without hidden layer:") 
print(output_data)

Output without hidden layer:
[[0.7 1. ]
 [1.5 2.2]
 [2.3 3.4]]


In [2]:
# 2. Forward Pass with Hidden Layer (Matrix Multiplication)
import numpy as np

# Input data (a 3x2 matrix) 
input_data = np.array([[1, 2], [3, 4], [5, 6]])

# Weight matrices (2 hidden units, 2 input features) 
weights_hidden = np.array([[0.1, 0.2], [0.3, 0.4]])

# Weight matrices (2 output units, 2 hidden units) 
weights_output = np.array([[0.5, 0.6], [0.7, 0.8]])

# Forward pass with a hidden Layer (matrix multiplication) 
hidden_layer_output = np.dot (input_data, weights_hidden)
output_data = np.dot (hidden_layer_output, weights_output)

print("Output with hidden layer: ")
print (output_data)

Output with hidden layer: 
[[1.05 1.22]
 [2.29 2.66]
 [3.53 4.1 ]]


In [3]:
#3. Forward Pass with Matrix Multiplication using Keras:

import numpy as np 
from keras.models import Sequential 
from keras.layers import Dense

# Input data (a 3x2 matrix)
input_data = np.array([[1, 2],
                        [3, 4],
                        [5, 6]])

# Define the Keras model
model = Sequential() 
model.add(Dense (units=2, input_dim=2, activation='sigmoid')) 
model.add(Dense (units=2, activation='sigmoid'))

#Weight matrices will be automatically initialized by Keras

# Perform the forward pass using Keras 

output_data = model.predict(input_data)

print("Output with Keras: ") 
print (output_data)

1/1 [==============================] - 1s 526ms/step
Output with Keras: 
[[0.6689358  0.38194644]
 [0.69333285 0.39228296]
 [0.697369   0.39166784]]


In [4]:
#4. Forward Pass with hidden layer  (Matrix Multiplication) using Keras:

import numpy as np 
from keras.models import Sequential 
from keras.layers import Dense

# Input data (a 3x2 matrix)
input_data = np.array([[1, 2],
                        [3, 4],
                        [5, 6]])

# Define the Keras model
model = Sequential() 

# Add a hidden Layer with 2 units and input dimension 2, using matrix multiplication 
model.add(Dense (units=2, input_dim=2, activation='sigmoid'))

# Add the output Layer with 2 units, also using matrix multiplication 
model.add(Dense (units=2, activation='sigmoid'))

#Weight matrices will be automatically initialized by Keras

# Perform the forward pass using Keras 

output_data = model.predict(input_data)

print("Output with Keras: ") 
print (output_data)

1/1 [==============================] - 0s 123ms/step
Output with Keras: 
[[0.4521883  0.70588464]
 [0.44500342 0.7318783 ]
 [0.4404269  0.74676627]]
